Data for this project is sourced from https://www.kaggle.com/datasets/meirnizri/covid19-dataset.

In [2]:
import numpy as np
import pandas as pd
import pickle

In [4]:
df = pd.read_csv('Covid_Data.csv')

In [5]:
df.head(10)

USMER  MEDICAL_UNIT  SEX  PATIENT_TYPE   DATE_DIED  INTUBED  PNEUMONIA  \
0      2             1    1             1  03/05/2020       97          1   
1      2             1    2             1  03/06/2020       97          1   
2      2             1    2             2  09/06/2020        1          2   
3      2             1    1             1  12/06/2020       97          2   
4      2             1    2             1  21/06/2020       97          2   
5      2             1    1             2  9999-99-99        2          1   
6      2             1    1             1  9999-99-99       97          2   
7      2             1    1             1  9999-99-99       97          1   
8      2             1    1             2  9999-99-99        2          2   
9      2             1    1             2  9999-99-99        2          2   

   AGE  PREGNANT  DIABETES  ...  ASTHMA  INMSUPR  HIPERTENSION  OTHER_DISEASE  \
0   65         2         2  ...       2        2             1              2   
1   72        97         2  ...       2        2             1              2   
2   55        97         1  ...       2        2             2              2   
3   53         2         2  ...       2        2             2              2   
4   68        97         1  ...       2        2             1              2   
5   40         2         2  ...       2        2             2              2   
6   64         2         2  ...       2        2             2              2   
7   64         2         1  ...       2        1             1              2   
8   37         2         1  ...       2        2             1              2   
9   25         2         2  ...       2        2             2              2   

   CARDIOVASCULAR  OBESITY  RENAL_CHRONIC  TOBACCO  CLASIFFICATION_FINAL  ICU  
0               2        2              2        2                     3   97  
1               2        1              1        2                     5   97  
2               2        2              2        2                     3    2  
3               2        2              2        2                     7   97  
4               2        2              2        2                     3   97  
5               2        2              2        2                     3    2  
6               2        2              2        2                     3   97  
7               2        2              1        2                     3   97  
8               2        1              2        2                     3    2  
9               2        2              2        2                     3    2  

[10 rows x 21 columns]

In [6]:
df.shape

(1048575, 21)

In [7]:
df.columns

Index(['USMER', 'MEDICAL_UNIT', 'SEX', 'PATIENT_TYPE', 'DATE_DIED', 'INTUBED',
       'PNEUMONIA', 'AGE', 'PREGNANT', 'DIABETES', 'COPD', 'ASTHMA', 'INMSUPR',
       'HIPERTENSION', 'OTHER_DISEASE', 'CARDIOVASCULAR', 'OBESITY',
       'RENAL_CHRONIC', 'TOBACCO', 'CLASIFFICATION_FINAL', 'ICU'],
      dtype='object')

In [8]:
df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 21 columns):
 #   Column                Non-Null Count    Dtype 
---  ------                --------------    ----- 
 0   USMER                 1048575 non-null  int64 
 1   MEDICAL_UNIT          1048575 non-null  int64 
 2   SEX                   1048575 non-null  int64 
 3   PATIENT_TYPE          1048575 non-null  int64 
 4   DATE_DIED             1048575 non-null  object
 5   INTUBED               1048575 non-null  int64 
 6   PNEUMONIA             1048575 non-null  int64 
 7   AGE                   1048575 non-null  int64 
 8   PREGNANT              1048575 non-null  int64 
 9   DIABETES              1048575 non-null  int64 
 10  COPD                  1048575 non-null  int64 
 11  ASTHMA                1048575 non-null  int64 
 12  INMSUPR               1048575 non-null  int64 
 13  HIPERTENSION          1048575 non-null  int64 
 14  OTHER_DISEASE         1048575 non-null  int64 
 15

In [9]:
df.nunique(axis=0)

USMER                     2
MEDICAL_UNIT             13
SEX                       2
PATIENT_TYPE              2
DATE_DIED               401
INTUBED                   4
PNEUMONIA                 3
AGE                     121
PREGNANT                  4
DIABETES                  3
COPD                      3
ASTHMA                    3
INMSUPR                   3
HIPERTENSION              3
OTHER_DISEASE             3
CARDIOVASCULAR            3
OBESITY                   3
RENAL_CHRONIC             3
TOBACCO                   3
CLASIFFICATION_FINAL      7
ICU                       4
dtype: int64

In [10]:
# show unique values
for col in df.columns:
    if df[col].nunique() > 20:
        pass
    else:
        print(col, ":\n  ", df[col].unique(), "\n")

USMER :
   [2 1] 

MEDICAL_UNIT :
   [ 1  2  3  4  5  6  7  8  9 10 11 12 13] 

SEX :
   [1 2] 

PATIENT_TYPE :
   [1 2] 

INTUBED :
   [97  1  2 99] 

PNEUMONIA :
   [ 1  2 99] 

PREGNANT :
   [ 2 97 98  1] 

DIABETES :
   [ 2  1 98] 

COPD :
   [ 2  1 98] 

ASTHMA :
   [ 2  1 98] 

INMSUPR :
   [ 2  1 98] 

HIPERTENSION :
   [ 1  2 98] 

OTHER_DISEASE :
   [ 2  1 98] 

CARDIOVASCULAR :
   [ 2  1 98] 

OBESITY :
   [ 2  1 98] 

RENAL_CHRONIC :
   [ 2  1 98] 

TOBACCO :
   [ 2  1 98] 

CLASIFFICATION_FINAL :
   [3 5 7 6 1 2 4] 

ICU :
   [97  2  1 99] 

